name: build-apps

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "**/TODO.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "**/TODO.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/setup

      - name: install dependencies
        run: pnpm i -r

        # Need to be able to run lint propely
      - name: build workspace dependency
        run: pnpm build:package

      - name: package build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: moon-sun-calc
          path: ./src/packages/moon-sun-calc/dist
          if-no-files-found: error

      - name: lint
        run: |
          pnpm run lint:code
          pnpm run lint:styles
          pnpm run lint:svelte

      - name: unit testing
        run: |
          pnpm run test:unit:ci

      - name: test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage
          if-no-files-found: error

      - name: build
        run: |
          pnpm run build:app

      - name: application build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: photo-companion
          path: ./src/apps/photo-companion/dist
          if-no-files-found: error
